### ISSUE TITLE
State of project

### ISSUE THREAD

**Issue by diclophis** [markaby/markaby#37]
As we approach 2017, I would like the current maintainers of this project please post their goals of the future of this project, and how we can ensure this project remains viable!

**Comment by smtlaissezfaire** [comment]
Hi @diclophis 

What would *you* like to see done with this project?

I've mostly stopped development on my end because of limited resources and the fact that I'm no longer using it at work.  I still love the project, though, and would love to see it thrive.

What are the things you'd like to see?

I'm completely open to opening it up the community - "rubinius style" - submit a patch that gets accepted and you become a maintainer.

**Comment by diclophis** [comment]
If anything I think I would like to be added as a maintainer of this project if possible.

I find markaby to be extremely value and still relevant for a wide variety of "micro web application" tasks

**Comment by diclophis** [comment]
@smtlaissezfaire Do you think it would be possible to add me as a contributor with PR merge access?

**Comment by smtlaissezfaire** [comment]
Hi @diclophis - I've added you to the project.  Go to town!

**Comment by diclophis** [comment]
Thanks! Long live the Markaby!
